# 创建文件上传表，负责动态图片保存
CREATE TABLE IF NOT EXISTS `file`(
 id INT PRIMARY KEY AUTO_INCREMENT,
 filename VARCHAR(100) NOT NULL UNIQUE,
 mimetype  VARCHAR(30),
 size INT,
 moment_id INT,
 user_id INT,
 createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES coderhub_users(id) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (moment_id) REFERENCES moment(id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8